// <auto-generated />
using LynxAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LynxAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250216215312_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LynxAPI.Models.Equipamento", b =>
                {
                    b.Property<string>("Instalacao")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Lote")
                        .HasColumnType("int");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Modelo")
                        .HasColumnType("int");

                    b.Property<string>("Operadora")
                        .IsRequired()
                        .HasColumnType("VARCHAR(5)");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Instalacao", "Lote");

                    b.ToTable("Equipamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
